name: datenguide
channels:
  - conda-forge
  - defaults
  - plotly
dependencies:
  # - ipython
  # - jupyter 
  - matplotlib
  - seaborn
  # - mkl
  - numpy
  - pandas>=0.25
  - pip
  - python=3.7
  - plotly
  - geopandas
  - geoviews
  - pip:
    - git+https://github.com/CorrelAid/datenguide-python.git
